name: news_app_demo
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  flutter_custom_carousel: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
